project_id = "vxwwhvticucuzrtnsrzv"

[functions.iptv-login]
verify_jwt = false

[functions.iptv-categories]
verify_jwt = false

[functions.stream-proxy]
verify_jwt = false

[functions.stream-token]
verify_jwt = false

[functions.stream-event]
verify_jwt = false

[functions.client-diagnostic]
verify_jwt = false

[functions.demo-creds]
verify_jwt = false
