REVOKE EXECUTE ON FUNCTION public.cleanup_client_diagnostics() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.cleanup_login_events() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.cleanup_stream_events() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.evict_idle_sessions() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.cleanup_used_nonces() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.cleanup_admin_audit_log() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.cleanup_tmdb_image_cache() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.cleanup_tmdb_episode_cache() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.cleanup_blocked_dns_failures() FROM anon, authenticated;